### PR TITLE
Improve identity v3 support

### PR DESCRIPTION
**Pull request by sbourlon**
OpenStack identity v3 instroduced domains which I added in this PR

- Add project domain and domain scoping
- Add user domain
- Add default domain in case the domain scope and the user domain are the same

Please, let me know if I am missing something or if this PR needs to be improved.

### CODE REVIEW

**Comment by jrperritt** [comment]
Thank you for the PR, but this repo is currently in feature-freeze mode. See #592

**Comment by sbourlon** [comment]
Thanks @jrperritt for the update. Would it still be possible to merge the PR after the feature-freeze mode is done?

**Comment by jrperritt** [comment]
>> Would it still be possible to merge the PR after the feature-freeze mode is done?

In this repo, no. In `gophercloud/gophercloud`, yes. The public APIs are nearly identical and compatible with one another. As in, almost all code using this library can switch to using the new library with a single `gofmt` command replacing the import lines, and it should just work. For code that does require changes, I'd expect them to be minor ones.

**Comment by sbourlon** [comment]
Thanks. I will test the PR against the new repo and sent a new PR to gophercloud/gophercloud.

**Comment by jrperritt** [comment]
Please read the description of #592 in its entirety. The new repo won't accept PRs until the contributing guide is updated and the API stabilized. You can track issue #592 for updates on the migration and status of the new repo.

**Comment by jrperritt** [comment]
Closing this. Hopefully we'll see it in the new repo

**Comment by fatmcgav** [comment]
@sbourlon / @jrperritt Any joy with making these changes against gophercloud/gophercloud?

**Comment by jtopjian** [comment]
@sbourlon @fatmcgav While reviewing https://github.com/hashicorp/terraform/pull/7041, I spent the past few evenings looking over the current gophercloud/gophercloud v3 implementation and I think everything is already in place. I even went as far as re-implementing the scoping portion of this PR and saw that the end result was the same.

While there is no direct support for `OS_PROJECT_DOMAIN_*`, `OS_USER_DOMAIN_*`, and `OS_DEFAULT_DOMAIN`, by using the correct combinations of `User*`, `Domain*`, and `Project*`, you can achieve the correct scoping.

_However_, I could be wrong. If so, can someone please provide an example of where scoping still needs work in the new Gophercloud repository?

**Comment by fatmcgav** [comment]
@jtopjian I'm inclined to agree, as I've been running TF using the latest code and using domain and project scoping quite happily. 

Cheers 
Gav

**Pull request closed without merging**
