### PR TITLE
[rfr]Add test for detecting misformatted code

### PR DESCRIPTION
**Pull request by pratikmallya**
Also fixes formatting in code that was not formatted correctly

### CODE REVIEW

**Comment by jrperritt** [comment]
This is a good idea. Is this just a unit test that will cause Travis to fail if there are any formatting issues?

**Comment by pratikmallya** [comment]
@jrperritt exactly

**Comment by pratikmallya** [comment]
@jrperritt perhaps a better way to do this would be to add this to the travis test itself? I'm kinda leaning towards that instead of having a unit test like this one

**Comment by jrperritt** [comment]
That's what I'm thinking, too

**Comment by jrperritt** [comment]
Closing in favor of checking during build.

**Pull request closed without merging**
