### PR TITLE
add image.Delete operation

### PR DESCRIPTION
**Pull request by spheromak**
This operation is documented in the docs, but was not implemented. So lets implement it!

http://gophercloud.io/docs/compute/#delete-image

### CODE REVIEW

**Comment by jrperritt** [comment]
Ah, quite right, thank you for the PR :)  Just a few suggestions to make it a bit more consistent with the other functions:

2. Adding a [unit test](https://github.com/rackspace/gophercloud/blob/master/openstack/compute/v2/images/requests_test.go)
3. Adding a function called `deleteURL` (in [`urls.go`](https://github.com/rackspace/gophercloud/blob/master/openstack/compute/v2/images/urls.go)) and using it instead of `getURL`. No need to add a unit test for `deleteURL`; We've deprecated that practice :)

**Comment by spheromak** [comment]
I went to add a test, but I don't understand what test I could add here to add value. Everything that is being used is already covered via the middleware functions. we simply take the string throw it against the api and return any error.

**Comment by spheromak** [comment]
@jrperritt fixed up per your feedback

**Comment by jrperritt** [comment]
Thank you :smile: 

:rocket:

**Pull request merged**
