### PR TITLE
Add Update operation for Rackspace servers

### PR DESCRIPTION
**Pull request by jrperritt**

### CODE REVIEW

**Comment by jamiehannaford** [comment]
Sorry to be a pain, but can we have some acceptance/unit tests :smile_cat: An extra fn on [L200](https://github.com/rackspace/gophercloud/blob/master/acceptance/rackspace/compute/v2/servers_test.go#L200) and [anywhere here](https://github.com/rackspace/gophercloud/blob/master/rackspace/compute/v2/servers/requests_test.go) would be awesome

**Comment by jrperritt** [comment]
Sure :)

**Comment by jrperritt** [comment]
There we go.

**Comment by jrperritt** [comment]
Self-merging :shipit:

**Pull request merged**
