### PR TITLE
Add more APIs for Cinder

### PR DESCRIPTION
**Pull request by feiskyer**
Add more APIs for Cinder:

* attach
* detach
* reserve
* unreserve
* initialize_connection
* terminate_connection

### CODE REVIEW

**Comment by feiskyer** [comment]
cc @jrperritt @smashwilson   

Will someone merge this PR?

**Comment by jamiehannaford** [comment]
@feiskyer Don't these operations belong in [Cinder v2](http://developer.openstack.org/api-ref-blockstorage-v2.html)? You've added them to the v1 package.

**Comment by feiskyer** [comment]
@jamiehannaford  Those APIs are not list at [Cinder v2](http://developer.openstack.org/api-ref-blockstorage-v2.html) and [Cinder v1](http://developer.openstack.org/api-ref-blockstorage-v1.html), but they are both working.

**Comment by jrperritt** [comment]
Where are these actions documented? I see the `attach` action [here](http://developer.openstack.org/api-ref-blockstorage-v2.html#volume-api-v2-volumes-actions) but not the rest.

**Comment by feiskyer** [comment]
@jrperritt There actions are defined at [here](https://github.com/openstack/cinder/blob/master/cinder/api/contrib/volume_actions.py). They are called directly by nova, but unfortunately not documented. These apis are useful for those who don't need nova.

**Comment by jrperritt** [comment]
Ah, OK. At the least, these operations should be moved the the `v2` package, and unit and acceptance tests should be added. Though they may work with `v1`, I'd prefer to add new functionality to the non-deprecated version.

**Comment by feiskyer** [comment]
@jrperritt #485 committed

**Comment by jrperritt** [comment]
Closing in favor of #485 ; I think that PR contains all this and more. @feiskyer let me know if that's not the case.

**Comment by feiskyer** [comment]
@jrperritt #485 contains all this and more, It's OK to close this one.

**Pull request closed without merging**
